image: "rust:latest"

stages:
  - build
  - test
  - deploy

# a single step to avoid caching libraries
build-and-verify-kurzlink:
  stage: build
  cache:
    key: cargo-cache
    paths:
      - target/
  artifacts:
    paths:
      - target/debug/kurzlink
  script:
    - cargo build
    - rustup component add clippy
    - cargo clippy -- -D warnings
    - cargo test

test-kurzlink-input-file:
  stage: test
  dependencies:
    - build-and-verify-kurzlink
  script:
    # hier das nocheck wegnehmen, da da ja ein falscher link drin ist
    - ./kurzlink --nocheck

generate-files:
  stage: deploy
  dependencies:
    - build-and-verify-kurzlink
  artifacts:
    paths:
      - public/
  script:
    - cargo run -- --nocheck --generate
    - ls